### ISSUE TITLE
TestScalaEngine gets confused when there are two JVMs trying to use it on the same machine at the same time

### ISSUE THREAD

**Issue by marmbrus** [radlab/SCADS#28] opened 2010-10-13 06:41 UTC
To reproduce:

Open two scala consoles.

scala1> TestScalaEngine.getTestCluster.getNamespace[StringRec, StringRec]("test")

scala2> TestScalaEngine.getTestCluster.getNamespace[IntRec, IntRec]("test")

**Comment by stephentu** [comment] 2010-10-13 22:06
what do you mean by "gets confused"?

you are trying to get the same namespace "test", but in scala1 you use StringRecs and in scala2 you use IntRecs. therefore, there should be an error.

here's what i'm able to reproduce:

scala1> TestScalaEngine.getTestCluster
scala1> res0.getNamespace[IntRec, IntRec]("test")

scala2> TestScalaEngine.getTestCluster
scala2> res0.getNamespace[StringRec, StringRec]("test")
java.lang.RuntimeException: Server key schema {"type":"record","name":"IntRec","namespace":"edu.berkeley.cs.scads.comm","fields":[{"name":"f1","type":"int"}]} is not a prefix of client key schema {"type":"record","name":"StringRec","namespace":"edu.berkeley.cs.scads.comm","fields":[{"name":"f1","type":"string"}]}

now, if in scala2 i do the following:

scala2> res0.getNamespace[IntRec, IntRec]("test")
scala2> res1.put(IntRec(1), IntRec(1))

and i go back to scala1:

scala1> res1.get(IntRec(1))
res2: Option[edu.berkeley.cs.scads.comm.IntRec] = Some({"f1": 1})

this seems to be expected behavior

**Comment by marmbrus** [comment] 2010-10-14 17:36
I think that calling getTestCluster should return district clusters when called from different JVMs.  Otherwise tests get messed up when you leave a console running.

**Comment by stephentu** [comment] 2010-10-15 19:37
k this is now fixed

**Closed as completed by stephentu** 2010-10-15 19:37 UTC
